### ISSUE TITLE
Tests hang on Windows

### ISSUE THREAD

**Issue by jednano** [postcss/postcss-parser-tests#2]
Not sure why, but the tests are hanging on Windows:

```
/.../GitHub/postcss-parser-tests (master * u=)
15:04 $npm test

> postcss-parser-tests@0.0.0 test z:\Documents\GitHub\postcss-parser-tests
> gulp

[15:04:17] Using gulpfile z:\Documents\GitHub\postcss-parser-tests\gulpfile.js
[15:04:17] Starting 'lint'...
[15:04:18] Starting 'integration'...
[15:04:18] Finished 'lint' after 678 ms
[15:04:30] Test GitHub styles
[15:04:30]      index-e85c4df2f00f610f7d403b70cb6ff08a89f810737918e84973d175e3c3
e31f50.css
e16acc4210448c9b0773934e1ba3eb3e212ebddf.css
[15:04:30]      index-54928a1b652a0e5eae929d39e16acc4210448c9b0773934e1ba3eb3e21
2ebddf.css
```

Maybe load-resources is not working properly? Because these are the only two resources I ever get.

**Comment by ai** [comment]
What is the error message? It is a good start of integration test. Then it is just stop?

**Comment by jednano** [comment]
Yeah. It just hangs. No error message. Doesn't exit cleanly. Just hangs there.

**Comment by jednano** [comment]
I have to `Ctrl+C` to exit after minutes of waiting.

**Comment by ai** [comment]
It could works few minutes.

**Comment by jednano** [comment]
OK I'll try a longer test.

**Comment by jednano** [comment]
Yep. Took 5 whole minutes :)

**Comment by alibby251** [comment]
I know this is an old thread, but I've just been experimenting with the plugin - it takes a good couple of mins on a Windows platform (Win10).

I've tried removing this line from real.js, which is part of the plugin:

```
var sites = [
    ['GitHub',    'https://github.com/'],
    ['Twitter',   'https://twitter.com/'],
    ['Bootstrap', 'github:twbs/bootstrap:dist/css/bootstrap.css'],
    ['Habrahabr', 'http://habrahabr.ru/']
];
```

..and replaced it with 
`var sites = [];`.

This makes it much quicker - is there any need to have these sites included, or should it be made clearer that these can be removed?

**Comment by ai** [comment]
@alibby251 you just remove sites, which is used in tests. Of course, it will become much quicker, because you tell to `postcss-parser-tests` test 0 sizes instead of 4.

**Comment by alibby251** [comment]
Hehe - yep, that is true! I was wondering though if this may have 
contributed to the issues with speed; I did also see a timeout error 
when first running the plugin too.

Perhaps something could be put on the site to indicate that the sites 
listed in the plugin can be removed? ;-)

**Comment by ai** [comment]
@alibby251 do you use this test to test PostCSS plugin?

**Comment by alibby251** [comment]
I was using it to test some CSS generated using the postcss-scss, 
postcss-nested and autoprefixer plugins; is that not the intended purpose?

**Comment by ai** [comment]
@alibby251 nope. This tests is for parser. For tools to parse input string into a nodes AST. For example I uses this tests to test `postcss` default parser, `postcss-scss` and `postcss-safe-parser`.

**Comment by alibby251** [comment]
Ah OK - oops! I'm not sure that the documentation makes it as clear as 
it could be for this though?

I think what tripped me up was this line:

```
let parser = require('./');
```
- this doesn't make it clear as to what ./ is referring to? I added in a 
  reference to the postcss-safe-parser plugin (you can see the full 
  details of how in issue #3); is what I've written there correct?

**Comment by ai** [comment]
```
let parser = require('./');
```

Because developer will test parser from parser development directory. For example, I uses `postcss-parser-tests` in `postcss/` project dir. So when I call `require('./')` I load current project in current dir.

**Comment by alibby251** [comment]
Okay...something's not right somewhere for me:

I changed that reference on my gulp file to this;

```
let parser = require('src/');
```
- this folder contains my CSS file (a single one called styles.css). I 
  reran the gulp task, to be returned this:

```
C:\wamp\www\postcss>gulp
[21:53:57] Using gulpfile C:\wamp\www\postcss\gulpfile.js
[21:53:57] Starting 'default'...
[21:53:57] 'default' errored after 3.65 ms
[21:53:57] Error: Cannot find module 'src/'
     at Function.Module._resolveFilename (module.js:325:15)
     at Function.Module._load (module.js:276:25)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Gulp.<anonymous> (C:\wamp\www\postcss\gulpfile.js:8:16)
     at module.exports (C:\wamp\www\postcss\node_modules\orchestrator\l
ib\runTask.js:34:7)
     at Gulp.Orchestrator._runTask (C:\wamp\www\postcss\node_modules\or
chestrator\index.js:273:3)
     at Gulp.Orchestrator._runStep (C:\wamp\www\postcss\node_modules\or
chestrator\index.js:214:10)
     at Gulp.Orchestrator.start (C:\wamp\www\postcss\node_modules\orche
strator\index.js:134:8)
     at C:\Users\alex\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
:129:20
```

Am I missing something here? To me, the error would suggest that it 
needs to see a module - all of my PostCSS modules are installed to 
node_modules though? Is this folder meant to store copies of plugin 
modules (as folders?) that I'm using within this project (so potentially 
doubling up on what is in node_modules)?

Apologies for the confusion - I just wanted to make sure I've got it 
right, and it would seem not! Hopefully you can see why I think we can 
improve on the documentation, to make it clearer...;-)

**Comment by ai** [comment]
Ouh. Sorry, but you need to learn npm first :(.

`require()` is not part of `postcss-parser-tests`. It is simple npm function, that loads JS files. So, when you write `require('./')` it loads `./index.js`. When you write `require('./src/other')` it loads `./src/other.js`.

It could not load directory. Also in default node it could not load CSS files (you can “load” CSS files only in webpack but it is completely different story).

**Comment by ai** [comment]
So if I run `require('./')` in `postcss` directory I will get postcss object:

``` js
var postcss = require('./');

postcss(plugins).process(css).css;
```

**Comment by alibby251** [comment]
Hehe - yep: I really need to get up to speed on NodeJS! ;-)

Based on what you've mentioned, if I include 
./node_modules/postcss-safe-parser in the require() statement, this 
should pick up this plugin as part of the tests. I've run it and it 
doesn't seem to have thrown any errors; have I got this right?

**Comment by ai** [comment]
@alibby251 let’s start from different side (I think you start in different place): what do you want to do?

**Comment by alibby251** [comment]
I'm trying to understand how the plugin example under "Integration" on 
the front page of the site works - it's so I can explain it as part of 
my upcoming book project ;-)

Space constraints mean I can't go into too complex detail within the 
book, but need enough to get people started. I think part of the problem 
is the documentation on the site doesn't give enough detail - yes, some 
of it is Node (and not part of the plugin), but I know that not everyone 
will know this, so need to give enough to get people going, and point 
them in the right direction for more details.

The code I have in my Gulp file at present is this:

```
'use strict';
var gulp = require('gulp');
var postcss = require('postcss');
var cases = require('postcss-parser-tests');

gulp.task('default', function (done) {
   let parser = require('./node_modules/postcss-safe-parser');
   cases.real(done, [['PostCSS', 
'http://localhost/postcss/src/styles.css']], function (css) {
     return parser(css).toResult({ map: { annotation: false } });
   });
});
```

This is based on the example from the front page, but adapted to test 
using the postcss-safe-parser plugin, with a CSS file hosted on a local 
webserver as the test for the callback. I'm not looking for it to be any 
more complicated at this stage, but will need to give some form of 
explanation as to what is happening?

**Comment by ai** [comment]
This tests is only for parser developers. Did your book contains section about developing custom parser?

**Comment by alibby251** [comment]
Yes it does - not in massive detail though (after all, the chapter has only 25 pages!).

I wanted to give a bit of an introduction / taster of what is possible - it's for this reason that not everything is covered, but I have covered things like using the postcss-safe-parser and postcss-scss plugins. I've then included something to show how you can manipulate the code (it's very basic, but it shows the principle), and pipe out both the changes and selected details from the AST tree. Other things are included, but they are not covered in detail - I want to show people what is possible to look at when they are more accustomed to using PostCSS, but not throw them into something that is very complex at this stage! ;-)

Does this make sense?

**Comment by alibby251** [comment]
PS - it's more about parsing code directly, rather than simply using plugins or developing a custom parser...

**Comment by ai** [comment]
Using existed custom parsers is not developing new custom parser 😉.

You don't need this tests for parsing CSS directly or to switching parsers.

Just remove this Gulp task.

**Comment by alibby251** [comment]
Fair point - I was hoping to show a flavor of what the tests would be like, but I can see it's not going to fit in with what I was expecting to do ;-)
I will make mention of it, but phrase it in a way that makes people aware that it is intended for developers only, and outside of the scope of this book. Leaving this aside though, and assuming I _had_ been writing a parser, is the Gulp task technically correct/set up properly for this?

**Comment by ai** [comment]
Nope, it is incorrect. The whole point of `cases.real` is to use real production CSS like Twitter, GitHub, BrowserHacks.

There is no sense to use it with your own CSS. You can parse and test it much easier.

**Comment by alibby251** [comment]
No worries - I won't include it. I suspect though this should be made clearer in the documentation though; it could be confusing for those just starting out on that path to creating custom parsers ;-)

Thanks for your help.
