### ISSUE TITLE
Add test cases for @supports with function syntax and pseudo selector

### ISSUE THREAD

**Issue by Dangoo** [postcss/postcss-parser-tests#20]
Just bumped into a compilation error using this ([valid](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports#testing_for_the_support_of_a_selector)) `@supports` rule:

```css
@support selector(:focus-visible) {
  .focussed-element:focus-visible {
    // Stuff here
  }
}
```

Since I had no clue where to start looking for the lack of support I thought maybe adding a test first and see where it breaks could be a good idea :)

Besides that here's my setup:
- Next.js
- PostCSS with CSS Modules
- React.js

Interestingly the following works without an issue:

```css
@support selector(.test) {
  .focussed-element:focus-visible {
    // Stuff here
  }
}
```

I'd be glad to help, just let know whether I may have missed smth or if you're open for contributions

**Comment by ai** [comment]
Good idea. I will add it today.

**Comment by ai** [comment]
Done d580c11 (PostCSS core parser has no problem with this example)
