### ISSUE TITLE
Incorrect source position for declarations that end with whitespace

### ISSUE THREAD

**Issue by romainmenke** [postcss/postcss-parser-tests#23]
https://github.com/postcss/postcss-parser-tests/blob/8f7e124764072f68add44611b8d68ec6aea8a82d/cases/custom-properties.json#L520-L524

Should be : 

```json
"end": {
   "offset": 541,
   "line": 30,
   "column": 12
 }
```

This is caused by the current tokenizer not setting start and end positions for whitespace : 
https://github.com/postcss/postcss/blob/main/lib/tokenize.js#L78

`currentToken = ['space', css.slice(pos, next)]`

**Comment by ai** [comment]
OK, let’s update the test when we will merge the new tokenizer

**Comment by romainmenke** [comment]
This is no longer relevant :)
