### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by alibby251** [postcss/postcss-parser-tests#3]
Hi,
I've been experimenting with the plugin on a Windows 10 platform - I think I have it working, but would like to confirm if I have it right please?

My Gulp file is this:

```
'use strict';
var gulp = require('gulp');
var postcss = require('postcss');
var cases = require('postcss-parser-tests');

gulp.task('default', function (done) {
  let parser = require('postcss-safe-parser');
  cases.real(done, [['PostCSS', 'http://localhost/postcss/src/styles.css']], function (css) {
    return parser(css).toResult({ map: { annotation: false } });
  });
});
```
- all of the plugins mentioned within are installed on my system.

When running the gulp task, I get these results:
![issue2](https://cloud.githubusercontent.com/assets/802739/14365787/66e396ec-fd07-11e5-87a5-fcabe8b61585.png)
My question - is this what we should expect to see when running the plugin, and do I have this configured correctly please?

**Comment by ai** [comment]
Sorry, I miss this issue :(. Feel free to ping me if I don’t answer again :)

**Comment by ai** [comment]
No, it is wrong behavior. Could you test it again on latest version?
