### ISSUE TITLE
Test fail with the parse of postcss

### ISSUE THREAD

**Issue by vipcxj** [postcss/postcss-parser-tests#9]
`apply.css` and `custom-properties.cc` are failed.
postcss version: 7.0.18
postcss-parser-tests version: 6.5.0
my test code:
```typescript
import { parse } from 'postcss';
import * as cases from 'postcss-parser-tests';
cases.each((name, css, ideal) => {
    it(`test ast of ${name}`, () => {
        const parsed = cases.jsonify(parse(css, { from: name }));
        expect(parsed).toEqual(ideal);
    })
})
```

**Comment by ai** [comment]
Everything works in `postcss/postcss` tests.

Why do you need to call PostCSS Parser Tests locally?

**Comment by vipcxj** [comment]
because I test my parser fail too, so I test the offical parser to see whether the bug from my code

**Comment by ai** [comment]
Maybe you have a problem with tests because of different operation system?

What is your OS?

Can you show the diff?

**Comment by vipcxj** [comment]
Mac OS
I check the source of `postcss/postcss/test/parse.test.js`, and found
```js
cases.each((name, css, json) => {
  if (name !== 'custom-properties.css') {
    it('parses ' + name, () => {
      let parsed = cases.jsonify(parse(css, { from: name }))
      expect(parsed).toEqual(json)
    })
  }
})
```
so `custom-properties.css` should be failed. now the problem is `apply.css`

**Comment by ai** [comment]
Show diff in failed tests

**Comment by vipcxj** [comment]
expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    @@ -7,62 +7,154 @@
        "nodes": [
          {
            "raws": {
              "before": "",
              "between": " ",
    -         "semicolon": true,
    +         "semicolon": false,
    +         "after": "\n"
    +       },
    +       "type": "rule",
    +       "nodes": [
    +         {
    +           "raws": {
    +             "before": "\n  ",
    +             "between": " ",
    +             "semicolon": true,
    -         "after": "\n"
    -       },
    +             "after": "\n  ",
    +             "ownSemicolon": ";"
    +           },
    -       "type": "rule",
    +           "type": "rule",
    -       "nodes": [
    +           "nodes": [
    -         {
    +             {
    -           "raws": {
    +               "raws": {
    -             "before": "\n  ",
    +                 "before": "\n    ",
    -             "between": ": "
    +                 "between": ": "
    -           },
    +               },
    -           "type": "decl",
    +               "type": "decl",
    -           "source": {
    +               "source": {
    -             "start": {
    +                 "start": {
    -               "line": 2,
    +                   "line": 3,
    -               "column": 3
    -             },
    +                   "column": 5
    +                 },
    -             "input": {
    +                 "input": {
    -               "file": "apply.css"
    +                   "file": "apply.css"
    -             },
    +                 },
    +                 "end": {
    +                   "line": 3,
    +                   "column": 13
    +                 }
    +               },
    -             "end": {
    +               "prop": "width",
    +               "value": "0"
    +             },
    +             {
    +               "raws": {
    +                 "before": "\n    ",
    +                 "between": ": "
    +               },
    +               "type": "decl",
    +               "source": {
    +                 "start": {
    -               "line": 5,
    -               "column": 4
    +                   "line": 4,
    +                   "column": 5
    +                 },
    +                 "input": {
    +                   "file": "apply.css"
    +                 },
    +                 "end": {
    +                   "line": 4,
    +                   "column": 14
    -             }
    +                 }
    -           },
    +               },
    -           "prop": "--zero-size",
    -           "value": "{\n    width: 0;\n    height: 0;\n  }"
    +               "prop": "height",
    +               "value": "0"
    +             }
    +           ],
    +           "source": {
    +             "start": {
    +               "line": 2,
    +               "column": 3
    +             },
    +             "input": {
    +               "file": "apply.css"
    +             },
    +             "end": {
    +               "line": 5,
    +               "column": 3
    +             }
    +           },
    +           "selector": "--zero-size:"
    +         },
    +         {
    +           "raws": {
    +             "before": "\n  ",
    +             "between": " ",
    +             "semicolon": true,
    +             "after": "\n  ",
    +             "ownSemicolon": "\n  ;"
    -         },
    -         {
    +           },
    +           "type": "rule",
    +           "nodes": [
    +             {
    -           "raws": {
    +               "raws": {
    -             "before": "\n  ",
    +                 "before": "\n    ",
    -             "between": ": ",
    -             "value": {
    +                 "between": ": "
    +               },
    +               "type": "decl",
    +               "source": {
    -               "value": "{\n    width: 16px;\n    height: 16px;\n  }",
    -               "raw": "{\n    width: 16px;\n    height: 16px;\n  }\n  "
    -             }
    -           },
    -           "type": "decl",
    +                 "start": {
    +                   "line": 7,
    +                   "column": 5
    +                 },
    +                 "input": {
    +                   "file": "apply.css"
    +                 },
    +                 "end": {
    +                   "line": 7,
    +                   "column": 16
    +                 }
    +               },
    +               "prop": "width",
    +               "value": "16px"
    +             },
    +             {
    +               "raws": {
    +                 "before": "\n    ",
    +                 "between": ": "
    +               },
    +               "type": "decl",
    -           "source": {
    +               "source": {
    -             "start": {
    +                 "start": {
    -               "line": 6,
    +                   "line": 8,
    -               "column": 3
    +                   "column": 5
    -             },
    +                 },
    -             "input": {
    +                 "input": {
    -               "file": "apply.css"
    +                   "file": "apply.css"
    -             },
    +                 },
    -             "end": {
    +                 "end": {
    -               "line": 10,
    -               "column": 3
    -             }
    +                   "line": 8,
    +                   "column": 17
    +                 }
    -           },
    +               },
    -           "prop": "--small-icon",
    -           "value": "{\n    width: 16px;\n    height: 16px;\n  }"
    +               "prop": "height",
    +               "value": "16px"
    +             }
    +           ],
    +           "source": {
    +             "start": {
    +               "line": 6,
    +               "column": 3
    +             },
    +             "input": {
    +               "file": "apply.css"
    +             },
    +             "end": {
    +               "line": 9,
    +               "column": 3
    +             }
    +           },
    +           "selector": "--small-icon:"
              }
            ],
            "source": {
              "start": {
                "line": 1,

**Comment by vipcxj** [comment]
I think `each` return `custom-properties.css` is a bug?

**Comment by ai** [comment]
Sorry, I have no idea. Since it is environment problem, seems like you need to debug the code on your own.

**Comment by vipcxj** [comment]
why it is environment problem?

**Comment by ai** [comment]
Because parser tests work on my laptop and on Travis CI.

Try to clone `postcss/postcss` and call `yarn` and `yarn test` there. It will call parser tests.

**Comment by vipcxj** [comment]
@ai see this [commit](https://github.com/postcss/postcss-parser-tests/commit/d27dd9bbda796a986aabf511abf29ef697ba179e)
I think this is the cause

**Comment by ai** [comment]
You need to user older Parser Test with PostCSS 6.

Latest Parser Test was created for future PostCSS 7.

Downgrade Parser Test https://github.com/postcss/postcss/blob/master/package.json#L67

**Comment by vipcxj** [comment]
If parser test is for postcss 7, I think the version should be 7.x too~

**Comment by ai** [comment]
It was a origin idea to copy PostCSS version, but then I found that it is not useful
